# Generated by Django 5.1 on 2024-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('data_inicio', models.DateField()),
                ('nota', models.IntegerField()),
                ('sobre', models.CharField(max_length=300)),
                ('exemplo1', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo2', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo3', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo4', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo5', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo6', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo7', models.ImageField(blank=True, null=True, upload_to='matheus/')),
                ('exemplo8', models.ImageField(blank=True, null=True, upload_to='matheus/')),
            ],
        ),
    ]
