# Generated by Django 5.1 on 2024-08-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matheus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbie',
            old_name='imagem',
            new_name='image',
        ),
    ]
