# Generated by Django 5.1 on 2024-08-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matheus', '0003_namorado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo1',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo2',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo3',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo4',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo5',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo6',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo7',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='exemplo8',
        ),
    ]
