# Generated by Django 5.1 on 2024-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matheus', '0004_remove_hobbie_exemplo1_remove_hobbie_exemplo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namorado',
            name='ele_traiu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='namorado',
            name='eu_trai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namorado',
            name='voltaria_a_namorar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='namorado',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
