# Generated by Django 5.1 on 2024-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matheus', '0005_namorado_ele_traiu_namorado_eu_trai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
